const assert = require('node:assert/strict');
const {createStore} = require('./storage.js');
const saved = new Map();
const storage = {getItem:key => saved.get(key) ?? null, setItem:(key,value) => saved.set(key,value)};
const first = createStore(storage, '2026-2027:live:8');
assert.deepEqual(first.read().choices, {});
first.save('Arsenal', '101');
first.save('Chelsea', '202');
const visit = createStore(storage, '2026-2027:live:8');
assert.deepEqual(visit.read().choices, {Arsenal:'101', Chelsea:'202'});
assert.deepEqual(createStore(storage, '2026-2027:live:9').read().choices, {});
assert.deepEqual(createStore(storage, '2026-2027:demo:8').read().choices, {});
assert.deepEqual(createStore(storage, '2027-2028:live:8').read().choices, {});
// Edits in separate tabs merge without replacing other clubs.
first.save('Arsenal','303');
visit.save('Chelsea','404');
assert.deepEqual(first.read().choices,{Arsenal:'303',Chelsea:'404'});
visit.save('Arsenal',null);
assert.equal(createStore(storage,'2026-2027:live:8').read().choices.Arsenal,null);
const blocked=createStore({getItem(){throw Error('blocked')},setItem(){throw Error('blocked')}},'blocked');
assert.ok(blocked.read().error);
assert.equal(blocked.save('Arsenal','101').choices.Arsenal,'101');
assert.equal(blocked.read().choices.Arsenal,'101');
const quota=createStore({getItem(){return '{}'},setItem(){throw Error('quota')}},'quota');
assert.ok(quota.save('Arsenal','505').error);
assert.equal(quota.read().choices.Arsenal,'505');
saved.set('iml:captains:v1:broken','invalid-json');
assert.ok(createStore(storage,'broken').read().error);
saved.clear();
assert.deepEqual(visit.read().choices,{});
console.log('PASS: restore after new visit, scope isolation, edits from multiple tabs, clear, blocked storage, quota, malformed data.');
